export interface Company {
  id: string
  name: string
  industry: string
  location: string
  employees: number
  founded: number
  revenue: string
  description: string
  website: string
  logo: string
}

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "TechVision Inc",
    industry: "Technology",
    location: "San Francisco, CA",
    employees: 1250,
    founded: 2015,
    revenue: "$125M",
    description: "Leading provider of cloud infrastructure solutions",
    website: "techvision.com",
    logo: "/tech-company-logo.jpg",
  },
  {
    id: "2",
    name: "Global Finance Corp",
    industry: "Finance",
    location: "New York, NY",
    employees: 3500,
    founded: 2008,
    revenue: "$450M",
    description: "International financial services and investment banking",
    website: "globalfinance.com",
    logo: "/finance-company-logo.png",
  },
  {
    id: "3",
    name: "HealthPlus Medical",
    industry: "Healthcare",
    location: "Boston, MA",
    employees: 2100,
    founded: 2012,
    revenue: "$280M",
    description: "Innovative healthcare technology and telemedicine platform",
    website: "healthplus.com",
    logo: "/healthcare-company-logo.png",
  },
  {
    id: "4",
    name: "EcoEnergy Solutions",
    industry: "Energy",
    location: "Austin, TX",
    employees: 850,
    founded: 2018,
    revenue: "$95M",
    description: "Renewable energy and sustainable power solutions",
    website: "ecoenergy.com",
    logo: "/energy-company-logo.jpg",
  },
  {
    id: "5",
    name: "DataStream Analytics",
    industry: "Technology",
    location: "Seattle, WA",
    employees: 680,
    founded: 2019,
    revenue: "$72M",
    description: "Big data analytics and business intelligence platform",
    website: "datastream.com",
    logo: "/data-analytics-logo.jpg",
  },
  {
    id: "6",
    name: "RetailMax Group",
    industry: "Retail",
    location: "Chicago, IL",
    employees: 5200,
    founded: 2005,
    revenue: "$620M",
    description: "Multi-channel retail and e-commerce solutions",
    website: "retailmax.com",
    logo: "/abstract-retail-logo.png",
  },
  {
    id: "7",
    name: "AutoDrive Technologies",
    industry: "Automotive",
    location: "Detroit, MI",
    employees: 1800,
    founded: 2016,
    revenue: "$210M",
    description: "Autonomous vehicle technology and AI systems",
    website: "autodrive.com",
    logo: "/automotive-tech-logo.jpg",
  },
  {
    id: "8",
    name: "CloudNine Software",
    industry: "Technology",
    location: "San Francisco, CA",
    employees: 420,
    founded: 2020,
    revenue: "$48M",
    description: "SaaS platform for enterprise collaboration",
    website: "cloudnine.com",
    logo: "/cloud-software-logo.png",
  },
  {
    id: "9",
    name: "BioPharm Research",
    industry: "Healthcare",
    location: "San Diego, CA",
    employees: 950,
    founded: 2013,
    revenue: "$135M",
    description: "Pharmaceutical research and drug development",
    website: "biopharm.com",
    logo: "/pharmaceutical-logo.jpg",
  },
  {
    id: "10",
    name: "FinTech Innovations",
    industry: "Finance",
    location: "New York, NY",
    employees: 580,
    founded: 2017,
    revenue: "$89M",
    description: "Digital payment solutions and blockchain technology",
    website: "fintechinno.com",
    logo: "/fintech-logo.png",
  },
  {
    id: "11",
    name: "EduLearn Platform",
    industry: "Education",
    location: "Cambridge, MA",
    employees: 320,
    founded: 2019,
    revenue: "$42M",
    description: "Online learning and educational technology",
    website: "edulearn.com",
    logo: "/education-tech-logo.png",
  },
  {
    id: "12",
    name: "MediaStream Studios",
    industry: "Media",
    location: "Los Angeles, CA",
    employees: 1100,
    founded: 2014,
    revenue: "$165M",
    description: "Digital media production and streaming services",
    website: "mediastream.com",
    logo: "/generic-media-logo.png",
  },
  {
    id: "13",
    name: "AgriTech Farms",
    industry: "Agriculture",
    location: "Des Moines, IA",
    employees: 450,
    founded: 2016,
    revenue: "$58M",
    description: "Smart farming and agricultural technology solutions",
    website: "agritech.com",
    logo: "/agriculture-tech-logo.jpg",
  },
  {
    id: "14",
    name: "CyberShield Security",
    industry: "Technology",
    location: "Washington, DC",
    employees: 720,
    founded: 2015,
    revenue: "$98M",
    description: "Cybersecurity and threat intelligence platform",
    website: "cybershield.com",
    logo: "/cybersecurity-logo.png",
  },
  {
    id: "15",
    name: "LogiChain Solutions",
    industry: "Logistics",
    location: "Memphis, TN",
    employees: 2800,
    founded: 2010,
    revenue: "$340M",
    description: "Supply chain management and logistics optimization",
    website: "logichain.com",
    logo: "/logistics-company-logo.png",
  },
  {
    id: "16",
    name: "SpaceX Ventures",
    industry: "Aerospace",
    location: "Houston, TX",
    employees: 1500,
    founded: 2011,
    revenue: "$220M",
    description: "Aerospace engineering and satellite technology",
    website: "spacexventures.com",
    logo: "/aerospace-company-logo.jpg",
  },
  {
    id: "17",
    name: "FoodTech Delivery",
    industry: "Food & Beverage",
    location: "Portland, OR",
    employees: 890,
    founded: 2018,
    revenue: "$112M",
    description: "Food delivery platform and restaurant technology",
    website: "foodtech.com",
    logo: "/food-delivery-logo.png",
  },
  {
    id: "18",
    name: "PropTech Realty",
    industry: "Real Estate",
    location: "Miami, FL",
    employees: 640,
    founded: 2017,
    revenue: "$85M",
    description: "Real estate technology and property management",
    website: "proptech.com",
    logo: "/real-estate-tech-logo.jpg",
  },
  {
    id: "19",
    name: "GreenBuild Construction",
    industry: "Construction",
    location: "Denver, CO",
    employees: 1200,
    founded: 2009,
    revenue: "$175M",
    description: "Sustainable construction and green building solutions",
    website: "greenbuild.com",
    logo: "/construction-company-logo.png",
  },
  {
    id: "20",
    name: "TravelHub Global",
    industry: "Travel",
    location: "Orlando, FL",
    employees: 950,
    founded: 2014,
    revenue: "$145M",
    description: "Travel booking platform and hospitality services",
    website: "travelhub.com",
    logo: "/travel-company-logo.png",
  },
]

export const industries = [
  "All Industries",
  "Technology",
  "Finance",
  "Healthcare",
  "Energy",
  "Retail",
  "Automotive",
  "Education",
  "Media",
  "Agriculture",
  "Logistics",
  "Aerospace",
  "Food & Beverage",
  "Real Estate",
  "Construction",
  "Travel",
]

export const locations = [
  "All Locations",
  "San Francisco, CA",
  "New York, NY",
  "Boston, MA",
  "Austin, TX",
  "Seattle, WA",
  "Chicago, IL",
  "Detroit, MI",
  "San Diego, CA",
  "Cambridge, MA",
  "Los Angeles, CA",
  "Des Moines, IA",
  "Washington, DC",
  "Memphis, TN",
  "Houston, TX",
  "Portland, OR",
  "Miami, FL",
  "Denver, CO",
  "Orlando, FL",
]